### ISSUE TITLE
401 unauthorized error coming for all hits 

### ISSUE THREAD

**Issue by rohitjoins** [dbrent-amazon/amazon-advertising-api-python#2]
Hey ,

I have fetched access token and refresh token from "Login with Amazon" services and registered & whitelisted my app. I am unable to fetch any data as it says 401 unauthorized access. I want data for Indian marketplace. It's not mentioned anywhere that amazon doesn't give the data for Indian marketplace however only -> 
https://advertising-api.amazon.com | North America (NA). Covers US and CA marketplaces
https://advertising-api-eu.amazon.com | Europe (EU). Covers UK, FR, IT, ES, and DE marketplaces
https://advertising-api-fe.amazon.com | Far East (FE). Covers JP marketplace. Can we fetch it?

**Comment by dbrent-amazon** [comment]
Hello,

You should have received a link to Jira Service Desk. Please open a ticket there as that is our official support channel.

**Comment by dbrent-amazon** [comment]
Sorry I didn't see the mention of IN. IN is not currently officially supported.

**Comment by rohitjoins** [comment]
hey,

I had a week trial for an add-on named SuperMetrics which fetches the reporting(marketing) data for Indian accounts , any idea how does it work with amazon APIs(Amazon advertising API) for IN markets?
P.S - any help would be appreciated.
